authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('', show_authentication, name='show_authentication'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
]

langganan/urls.py
from django.urls import path
from langganan.views import show_langganan, show_beli

app_name = 'langganan'

urlpatterns = [
    path('', show_langganan, name='show_langganan'),
    path('beli/', show_beli, name='show_beli'),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('authentication/', include('authentication.urls')),
    path('daftarkontributor/', include('daftarkontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('pengguna/', include('pengguna.urls')),
    path('tayangan/', include('tayangan.urls')),
    path('trailer/', include('trailer.urls')),
    path('ulasan/', include('ulasan.urls')),
]

tayangan/urls.py
from django.urls import path
from tayangan.views import *

app_name = 'tayangan'

urlpatterns = [
    path('', show_tayangan, name='show_tayangan'),
    path('pencarian', show_result, name='show_result'),
    path('detail-film/<str:id>', show_film, name='show_film'),
    path('detail-series/<str:id>', show_series, name='show_series'),
    path('detail-episode/<str:id_series>/<str:subjudul>',show_episode, name='show_episode'),
    path('tonton', add_riwayat_nonton, name='add_riwayat_nonton')
]

trailer/urls.py
from django.urls import path
from trailer.views import *

app_name = 'trailer'

urlpatterns = [
    path('', show_trailer, name='show_trailer'),
    path('pencarian', show_result, name='show_result'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PacilFlix</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <style>
    /* Custom CSS untuk mengatur tampilan navbar */
    .navbar-custom {
      background-color: #007bff;
      /* Warna latar belakang navbar */
    }

    .navbar-custom .navbar-brand,
    .navbar-custom .navbar-text {
      color: #ffffff;
      /* Warna teks navbar */
    }

    .navbar-custom .navbar-nav .nav-link {
      color: #ffffff;
    }

    .navbar-custom .navbar-nav .nav-link:hover {
      color: #ffffff;
    }
    body {
      padding-top: 40px;
    }
  </style>

  {% block meta %}
  {% endblock meta %}
</head>



<body >
  <nav class="navbar navbar-expand-lg navbar-custom fixed-top">
    <a class="navbar-brand" href="#">PacilFlix</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        {% if request.COOKIES.is_authenticated %}
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="{% url 'tayangan:show_tayangan' %}">Daftar Tayangan</a>
        </li>
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="{% url 'daftarkontributor:show_daftarkontributor' %}">Daftar Kontributor</a>
        </li>
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="#">Kelola Daftar Favorit</a>
        </li>
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="#">Kelola Daftar Unduhan</a>
        </li>
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="{% url 'langganan:show_langganan' %}">Kelola Langganan</a>
        </li>
        {% else %}
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="{% url 'tayangan:show_tayangan' %}">Daftar Trailer</a>
        </li>
        {% endif %}

      </ul>
      <ul class="navbar-nav ml-auto"> <!-- Menggunakan ml-auto untuk menggeser ke kanan -->
        {% if request.COOKIES.is_authenticated %}

        <li class="nav-item" id="user-nav-item">
          <button class="nav-link" id="logout-button">Logout</button>
        </li>
        {% else %}
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
        </li>
        <li class="nav-item" id="user-nav-item">
          <a class="nav-link" href="{% url 'authentication:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}
</body>

<script>
  const logoutButton = document.getElementById('logout-button');
  logoutButton.addEventListener('click', async () => {
    const response = await fetch('/authentication/logout/', {
      method: 'POST'
    })
    if (response.ok) {
      window.location.href = '/';
    }
  });
</script>

{% block script %}
{% endblock script %}

<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.2/js/bootstrap.min.js"></script>

</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %}
    <title>PacilFlix</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        /* Custom CSS untuk mengatur tampilan navbar */
        .navbar-custom {
            background-color: #007bff; /* Warna latar belakang navbar */
        }
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
            color: #ffffff; /* Warna teks navbar */
        }
        .navbar-custom .navbar-nav .nav-link {
            color: #ffffff;
        }
        .navbar-custom .navbar-nav .nav-link:hover {
            color: #ffffff;
        }
    </style>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">PacilFlix</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'trailer:show_trailer' %}">Trailer Tayangan</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item" id="login-nav-item">
                    <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
                </li>
            </ul>
        </div>
    </nav>

    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.2/js/bootstrap.min.js"></script>
    {% endblock meta %}
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>